services:

  haystack-api:
    image: "deepset/haystack:cpu-main"
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - PIPELINE_YAML_PATH=/config/pipelines.yaml
      - QUERY_PIPELINE_NAME=query
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./config:/config
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "true"
      cluster.routing.allocation.disk.watermark.low: "2gb"
      cluster.routing.allocation.disk.watermark.high: "1gb"
      cluster.routing.allocation.disk.watermark.flood_stage: "512mb"

  kibana:
    image: kibana:8.5.1
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
